name = "hugodzibetti/lattice"
version = "0.1.0"
description = "A blazing fast, size-efficient, backward-compatible Roblox Instance serializer."
authors = ["hugodzibetti"]
license = "MIT"
repository = "https://github.com/hugodzibetti/lattice"

[target]
environment = "roblox"
lib = "src/init.luau"

[engines]
lune = "0.10.4"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
test = "scripts/RunTests.luau"
artifact = "src/artifacts/build/Run.luau"
roundtrip = "scripts/RoundTrip.luau"
bench-pipeline = "bench/RunPipeline.luau"
build-package = "scripts/BuildPackage.luau"
lattice = "cli/Main.luau"

[dependencies]

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2", target = "lune" }
